const poemData = [
  {
    "id": 1,
    "language": "en",
    "image": "https://lh4.googleusercontent.com/f8-qatxxs3PvAORY3TakgI3WDPYoVojUXsUpvV2kQ5uGZH7pkObQK_K0SHiEihQqjPQWRUwBtJHv4HqxTYtGYaqA1uqztv6E0GCfa1HLsE0om0QbibzcJ7PCd0BRcav9R7nT2lTI",
    "poet": "Audre Lorde",
    "title": "A Woman Speaks",
    "lines" : [
      "Moon marked and touched by sun",
      "my magic is unwritten",
      "but when the sea turns back",
      "it will leave my shape behind.",
      "I seek no favor",
      "untouched by blood",
      "unrelenting as the curse of love",
      "permanent as my errors",
      "or my pride",
      "I do not mix",
      "love with pity",
      "nor hate with scorn",
      "and if you would know me",
      "look into the entrails of Uranus",
      "where the restless oceans pound.",
      "",
      "I do not dwell",
      "within my birth nor my divinities",
      "who am ageless and half-grown",
      "and still seeking",
      "my sisters",
      "witches in Dahomey",
      "wear me inside their coiled cloths",
      "as our mother did",
      "mourning.",
      "",
      "I have been woman",
      "for a long time",
      "beware my smile",
      "I am treacherous with old magic",
      "and the noon's new fury",
      "with all your wide futures",
      "promised",
      "I am",
      "woman",
      "and not white."
    ]
  },
  {
    "id": 2,
    "language": "en",
    "image": "https://www.poetrysociety.org/psa/poetry/crossroads/ars_poetica/carl_phillips/attachment_1.jpg",
    "poet": "Carl Phillips",
    "title": "Blue",
    "lines" : [
      "As through marble or the lining of",
      "certain fish split open and scooped",
      "clean, this is the blue vein",
      "that rides, where the flesh is even",
      "whiter than the rest of her, the splayed",
      "thighs mother forgets, busy struggling",
      "for command over bones: her own,",
      "those of the chaise longue, all",
      "equally uncooperative, and there’s",
      "the wind, too. This is her hair, gone",
      "from white to blue in the air.",
      "",
      "This is the black, shot with blue, of my dark",
      "daddy’s knuckles, that do not change, ever.",
      "Which is to say they are no more pale",
      "in anger than at rest, or when, as",
      "I imagine them now, they follow",
      "the same two fingers he has always used",
      "to make the rim of every empty blue",
      "glass in the house sing.",
      "Always, the same",
      "blue-to-black sorrow",
      "no black surface can entirely hide.",
      "",
      "Under the night, somewhere",
      "between the white that is nothing so much as",
      "blue, and the black that is, finally; nothing,",
      "I am the man neither of you remembers.",
      "Shielding, in the half-dark,",
      "the blue eyes I sometimes forget",
      "I don’t have. Pulling my own stoop-",
      "shouldered kind of blues across paper.",
      "Apparently misinformed about the rumored",
      "stuff of dreams: everywhere I inquired,",
      "I was told look for blue."
    ]
  },
  {
    "id": 3,
    "language": "en",
    "image": "https://static-secure.guim.co.uk/sys-images/Guardian/Pix/pictures/2014/2/17/1392646834480/Warsan-Shire-008.jpg",
    "poet": "Warsan Shire",
    "title": "For Women Who Are Difficult to Love",
    "lines": [
      "you are a horse running alone",
      "and he tries to tame you",
      "compares you to an impossible highway",
      "to a burning house",
      "says you are blinding him",
      "that he could never leave you",
      "forget you",
      "want anything but you",
      "you dizzy him, you are unbearable",
      "every woman before or after you",
      "is doused in your name",
      "you fill his mouth",
      "his teeth ache with memory of taste",
      "his body just a long shadow seeking yours",
      "but you are always too intense",
      "frightening in the way you want him",
      "unashamed and sacrificial",
      "he tells you that no man can live",
      "up to the one who",
      "lives in your head",
      "and you tried to change didn't you?",
      "closed your mouth more",
      "tried to be softer",
      "prettier",
      "less volatile, less awake",
      "but even when sleeping you could feel",
      "him travelling away from you in his dreams",
      "so what did you want to do love",
      "split his head open?",
      "you can't make homes out of human beings",
      "someone should have already told you that",
      "and if he wants to leave",
      "then let him leave",
      "you are terrifying",
      "and strange and beautiful",
      "something not everyone knows how to love."
    ]
  },
  {
    "id": 4,
    "language": "en",
    "image": "https://fatimahasghar.files.wordpress.com/2014/11/cropped-fatimah_portrait_01_jason-riker_.jpg",
    "poet": "Fatimah Asghar",
    "title": "If They Should Come for Us",
    "lines": [
        "these are my people and I find",
        "them on the street and shadow",
        "through any wild all wild",
        "my people my people",
        "a dance of strangers in my blood",
        "the old woman’s sari dissolving to wind",
        "bindi a new moon on her forehead",
        "I claim her my kin and sew",
        "the star of her to my breast",
        "the toddler dangling from stroller",
        "hair a fountain of dandelion seed",
        "at the bakery I claim them too",
        "the sikh uncle at the airport",
        "who apologizes for the pat",
        "down the muslim man who abandons",
        "his car at the traffic light drops",
        "to his knees at the call of the azan",
        "and the muslim man who sips",
        "good whiskey at the start of maghrib",
        "the lone khala at the park",
        "pairing her kurta with crocs",
        "my people my people I can’t be lost",
        "when I see you my compass",
        "is brown and gold and blood",
        "my compass a muslim teenager",
        "snapback and high-tops gracing",
        "the subway platform",
        "mashallah I claim them all",
        "my country is made",
        "in my people’s image",
        "if they come for you they",
        "come for me too in the dead",
        "of winter a flock of",
        "aunties step out on the sand",
        "their dupattas turn to ocean",
        "a colony of uncles grind their palms",
        "and a thousand jasmines bell the air",
        "my people I follow you like constellations",
        "we hear the glass smashing the street",
        "and the nights opening their dark",
        "our names this country’s wood",
        "for the fire my people my people",
        "the long years we’ve survived the long",
        "years yet to come I see you map",
        "my sky the light your lantern long",
        "ahead and I follow I follow"
    ]
  },
  {
    "id": 5,
    "language": "en",
    "image": "https://media.poetryfoundation.org/m/image/8374/Vang_Mai_Der",
    "poet": "Mai Der Vang",
    "title": "Last Body",
    "lines": [
      "I can’t leave my hurting skull",
      "Or the rose apple opening inside me.",
      "",
      "I’ll count the weeks, months,",
      "Unfurling each numbered day in my hair.",
      "",
      "Frost ribbons inside my brain,",
      "Canals push up my leg.",
      "",
      "I’m moving on",
      "To what the world needs me to know.",
      "",
      "I am the angel trapped inside the bullet.",
      "I am the exit wound trapped inside the angel.",
      "",
      "Am I the scarecrow",
      "Perched at the end of the human trail.",
      "",
      "I’ll palm cotton between my prayers",
      "Until the universe has passed,",
      "",
      "Waving down jellyfish",
      "To volcano hours.",
      "",
      "What force propels a bullet",
      "From its chamber. Is it sourced by water",
      "",
      "Trickling in a karst cave,",
      "Or is it an angel’s gasp as she flees.",
      "",
      "I can’t answer it all,",
      "But my mask grows taller every year."
    ]
  },
  {
    "id": 6,
    "language": "en",
    "image": "https://media.poetryfoundation.org/m/image/1239/Jess_Tyehimba1",
    "poet": "Tyehimba Jess",
    "title": "Blind Boone's Vision",
    "lines": [
      "When I got old enough",
      "I asked my mother,",
      "to her surprise,",
      "to tell me what she did",
      "with my eyes. She balked",
      "and stalled, sounding",
      "unsure for the first time",
      "I could remember.",
      "It was the tender way",
      "she held my face",
      "and kissed where tears",
      "should have rolled",
      "that told me I’d asked",
      "of her the almost impossible—",
      "to recount my blinding",
      "tale, to tell what became",
      "of the rest of me.",
      "She took me by the hand",
      "and led me to a small",
      "sapling that stood not",
      "much taller than me.",
      "I could smell the green",
      "marrow of its promise",
      "reaching free of the soil",
      "like a song from Earth’s",
      "royal, dirty mouth.",
      "Then Mother told me",
      "how she, newly freed,",
      "had prayed like a slave",
      "through the night when",
      "the surgeon took my eyes",
      "to save my fevered life,",
      "then got off her knees",
      "come morning to take",
      "the severed parts of me",
      "for burial—right there",
      "beneath that small tree.",
      "They fed the roots,",
      "climbed through its leaves",
      "to soak in sunlight . . .",
      "and so, she told me,",
      "I can see.",
      "",
      "When the wind rustles",
      "up and cools me down,",
      "when the earth shakes",
      "with footsteps and when",
      "the sound of birdcalls",
      "stirs forests like the black",
      "and white bustling",
      "’neath my fingertips",
      "I am of the light and shade",
      "of my tree. Now,",
      "ask me how tall",
      "that tree of mine",
      "has grown to be",
      "after all this time—",
      "it touches a place",
      "between heaven and here.",
      "And I shudder when I hear",
      "the earth’s wind",
      "in my bones",
      "through the bones",
      "of that boxed-up",
      "swarm of wood,",
      "bird and bee:",
      "I let it loose . . .",
      "and beyond",
      "me."
    ]
  },
  {
    "id": 7,
    "language": "en",
    "image": "https://www.poets.org/sites/default/files/styles/286x289/public/images/biographies/Lylee.jpg?itok=WRTXLenv",
    "poet": "Li-Young Lee",
    "title": "Eating Together",
    "lines": [
      "In the steamer is the trout",
      "seasoned with slivers of ginger,",
      "two sprigs of green onion, and sesame oil.",
      "We shall eat it with rice for lunch,",
      "brothers, sister, my mother who will",
      "taste the sweetest meat of the head,",
      "holding it between her fingers",
      "deftly, the way my father did",
      "weeks ago. Then he lay down",
      "to sleep like a snow-covered road",
      "winding through pines older than him,",
      "without any travelers, and lonely for no one."
    ]
  },
  {
    "id": 8,
    "language": "en",
    "image": "https://www.poetryfoundation.org/harriet/wp-content/uploads/2015/09/JFHerrera.jpeg",
    "poet": "Juan Felipe Herrera",
    "title": "Let Me Tell You What a Poem Brings",
    "lines": [
      "Before you go further,",
      "let me tell you what a poem brings,",
      "first, you must know the secret, there is no poem",
      "to speak of, it is a way to attain a life without boundaries,",
      "yes, it is that easy, a poem, imagine me telling you this,",
      "instead of going day by day against the razors, well,",
      "the judgments, all the tick-tock bronze, a leather jacket",
      "sizing you up, the fashion mall, for example, from",
      "the outside you think you are being entertained,",
      "when you enter, things change, you get caught by surprise,",
      "your mouth goes sour, you get thirsty, your legs grow cold",
      "standing still in the middle of a storm, a poem, of course,",
      "is always open for business too, except, as you can see,",
      "it isn’t exactly business that pulls your spirit into",
      "the alarming waters, there you can bathe, you can play,",
      "you can even join in on the gossip—the mist, that is,",
      "the mist becomes central to your existence."
    ]
  },
  {
    "id": 9,
    "language": "en",
    "image": "https://uwm.edu/english/wp-content/uploads/sites/109/2015/10/nprpoet_wide-17197616453dbacdaeb00b82105ca51403a79bf6.jpg",
    "poet": "Carmen Giménez Smith",
    "title": "The Daughter",
    "lines": [
      "We said she was a negative image of me because of her lightness.",
      "She's light and also passage, the glory in my cortex.",
      "Daughter, where did you get all that goddess?",
      "Her eyes are Neruda's two dark pools at twilight.",
      "Sometimes she's a stranger in my home because I hadn't imagined her.",
      "Who will her daughter be?",
      "She and I are the gradual ebb of my mother's darkness.",
      "I unfurl the ribbon of her life, and it's a smooth long hallway, doors flung open.",
      "Her surface is a deflection is why.",
      "Harm on her, harm on us all.",
      "Inside her, my grit and timbre, my reckless."
    ]
  },
  {
    "id": 10,
    "language": "en",
    "image": "https://media1.fdncms.com/chicago/imager/u/original/22550817/jamila_woods_005-teaser.jpg",
    "poet": "Jamila Woods",
    "title": "beverly, huh.",
    "lines": [
      "you must be",
      "made of money.",
      "your parents",
      "must have grown",
      "on trees.",
      "bet you’re black",
      "tinged with green.",
      "bet you sleep",
      "on bags of it.",
      "bet your barbies",
      "climb it.",
      "bet you never",
      "wanted.",
      "bet you never",
      "had to ask.",
      "bet you golf.",
      "bet you tennis.",
      "bet you got",
      "a summer house.",
      "bet you got",
      "a credit card",
      "for your 5th birthday.",
      "bet you played",
      "with bills for toys.",
      "bet you chew",
      "them up",
      "for dinner.",
      "bet you spit",
      "your black out",
      "like tobacco",
      "that’s why you talk so",
      "bet you listen to green day.",
      "bet you ain’t never heard of al.",
      "bet your daddy wears a robe",
      "around the house.",
      "bet his hands are soft as a frog’s belly.",
      "bet your house is on a hill.",
      "bet the grass is freshly cut.",
      "bet you feel like a princess.",
      "bet the police protect your house.",
      "bet you know their first names.",
      "bet your house has a hundred rooms.",
      "bet a black lady comes to clean them."
    ]
  },
]

export default poemData
